development:
  adapter: postgresql
  database: bill_settlement_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: bill_settlement_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: bill_settlement_production
  pool: 5
  timeout: 5000